language: go
sudo: required
go:
  - 1.8
  - tip

notifications:
  email: false

before_install:
    - go get -v github.com/Masterminds/glide
    - glide install
script:
  - test -z "$(gofmt -s -l . | tee /dev/stderr)"
  - go test -timeout 1m -v $(glide novendor)
  - make build
