name: "vflow"

on:
  push:
    branches:
      - master
    paths-ignore:
      - "docs/**"
      - "**.md"
  pull_request:
    branches:
      - master
    paths-ignore:
      - "docs/**"
      - "**.md"

jobs:
  test:
    name: Test
    strategy:
      matrix:
        go-version: [1.19.x, 1.20.x]
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Set up Golang
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Setup golang cache
        uses: actions/cache@v3
        with:
          path: |
              ~/go/pkg/mod
              ~/.cache/go-build
              ~/Library/Caches/go-build
              ~\AppData\Local\go-build
          key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
              ${{ runner.os }}-go-${{ matrix.go-version }}-

      - name: Check out code
        uses: actions/checkout@v3

      - name: Test
        run: make test

      - name: Build
        run: make build
